# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
