# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
