# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180312_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
