# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
